name: Build release binary

on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Build Release Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", amd64, arm64]
        exclude:  
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.21
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: clematis
        extra_files: LICENSE README.md
